### PR TITLE
Draft: Improve correctness of Portuguese (pt-PT) translations

### PR DESCRIPTION
**Pull request by Tmpod**
Hello!

Here's a little PR improving some of the translations done by @joaopmatos, which were otherwise well done :D  
Just fixes small mistakes and uses better terms in some cases.

I have a question, however (hence the draft tag) -- where is the "Drag Handle" string used? I've failed to find it within the app and I'm uncertain how it should best be translated. Getting the context for strings is crucial for good work here.

### CODE REVIEW

**Comment by OmGodse** [comment]
Make Lists

Drag Handle is used as the description for the icon so screen readers can know it's purpose

**Comment by Tmpod** [comment]
Alright, I will finish the patch and remove the draft label in a bit!

**Comment by MercerBoi** [comment]
Hello, I realise that this isn't the right place to ask this but I'm left with no choice. Is there any space left in this project for considering the feature requests of users? I see this GitHub doesn't have "Issues" or "Discussion" sections enabled so that's two methods of asking gone, I emailed the developer twice but was met with no response. I'm not getting any option to write a review on the Play Store either since I downloaded this from F-Droid. Hence I'm writing here hoping that the dev somehow sees this. So what's the stance regarding feature requests? I'd appreciate some clarification, thanks.

**Comment by OmGodse** [comment]
Hi, I think there might be an issue with your email since I haven't received any mails, even in the spam folder.

> So what's the stance regarding feature requests?

I'm not currently accepting feature requests, bug fixes and translations though, are welcome.

**Pull request closed without merging**
