### PR TITLE
Bug: Rare reverting memory bug to last savestate?

### PR DESCRIPTION
**Pull request by Snailhail**
Problem: encountered serious reverting memory bug 2 times during whole usage of dling app & writing stuff down.
 
Steps to reproduce: leave notepad doc file open to write, or view mode after writing abunch of text. Open app from home menu & It reverts back to last auto save point, or exported one unsure which one.  

TEMPORARY FIX: It's not permanent as long as no changes(written) are made. Closing the app will undo the bug IF NOT it will save the change.

### CODE REVIEW

**Comment by OmGodse** [comment]
Could you attach a screen recording of the bug?

**Comment by Snailhail** [comment]
> Could you attach a screen recording of the bug?
I made a edit to the title. It's seems to be a somewhat rare case. To  me recording 
several, different times of the days bearing no results. I can still confirm the save rewind happened despite not knowing 100℅ the exact conditions to get there. There was no intense apps running, or low storage that could cause it. Just  device settings, web browser, camera maybe opened while having Normally open.
Sorry, I can't provide much help.  All I can do Is keep monitoring incase It happens again.

**Comment by df71** [comment]
Also encountered this behaviour on GrapheneOS (Android 13; latest version). May be a device-specific issue?

**Comment by OmGodse** [comment]
I've still not been able to replicate it. It might be due to `onSaveInstanceState` note being called for certain devices.

**Comment by OmGodse** [comment]
It's a bit hackish but maybe a option to manually save will help users?

**Comment by df71** [comment]
> It's a bit hackish but maybe a option to manually save will help users?

Yes, this could be a workaround. If feasible and not already done, the best option would be to trigger the ```save``` operation by certain events (eg. when closing the app or focus changes).

**Comment by OmGodse** [comment]
> Please use the pull requests tab only for translations or bug fixes.

Please follow the guidelines in [CONTRIBUTING.md](https://github.com/OmGodse/Notally/blob/master/CONTRIBUTING.md). I'm not taking feature requests right now.

**Comment by OmGodse** [comment]
@Snailhail @df71

I've identified the bug, I'll write a detailed blog post later which I can link to so other developers can also avoid it but the gist is as follows.

1. User clicks on a note (Let's suppose it contains the text "Hello")
2. The selected note is passed as an extra to `NotallyActivity`
3. `NotallyActivity` receives the selected note and uses it to setup the initial state of `BaseNoteModel`. It then sets the `isFirstInstance` flag of `BaseNoteModel` to false. Let's suppose after this we type "World" so the entire text content is "Hello World". This is stored in `BaseNoteModel` and persisted to disk on orientation changes, when clicking back, etc. Since `BaseNoteModel` survives orientation changes, the same instance is returned after rotating the device whereas `NotallyActivity` will be recreated. It will then see that `isFirstInstance` is false and so use the data stored in `BaseNoteModel`.

**Start of abnormal behavior**

4. In case of system initiated process death, ViewModel instances are not persisted but the extras sent to an Activity and data stored in savedInstanceState is persisted. If after typing "Hello World", Notally is moved to the background and the process is killed (due to low memory), when the app is opened again, `NotallyActivity` sees the `isFirstInstance` flag of `BaseNoteModel` is true (because a new instance was created) and so uses the original note passed as an extra to setup it's state (which contains "Hello" instead of "Hello World")

I'll fix it in the next update.

https://developer.android.com/topic/libraries/architecture/saving-states

**Comment by df71** [comment]
Great news, good work!

**Comment by OmGodse** [comment]
Fixed in v5.3

**Pull request closed without merging**
