### PR TITLE
Brazilian portuguese translation

### PR DESCRIPTION
**Pull request by fabianski7**
🇧🇷

### CODE REVIEW

**Comment by OmGodse** [comment]
Yes exactly like that.

**Comment by fabianski7** [comment]
done

**Comment by OmGodse** [comment]
Please remove all the string resources with `translatable` set to false as they're already present in the main configuration (No need to duplicate them)

**Comment by fabianski7** [comment]
done.
I already contribute with several other translations and this was never requested. Maybe it's not that necessary

**Comment by OmGodse** [comment]
Thanks. It's necessary. What you're doing right now is creating a translation for another locale. The non translatable strings are already present in the current locale so there's no need to duplicate them.

**Comment by OmGodse** [comment]
Could you also say by which name you want me to accredit you on the list of translators? Your GitHub username or something else?

**Comment by fabianski7** [comment]
the username is enough. thanks

**Comment by OmGodse** [comment]
Could you please translate the following phrases for the next update? No need to make a separate pull request, you can just reply here

Pin
Unpin
Pinned

**Comment by fabianski7** [comment]
Of course.

> Pin

Fixar

> Unpin

Desafixar

> Pinned

Fixado

**Comment by OmGodse** [comment]
Thanks!

Could you please also translate the following phrases which'll be used in the upcoming update? (I'm attaching screenshots for context)

No need to make another pull request, you can just directly reply here.

Delete all
Delete all notes?
Delete all notes
Delete all

**Pull request merged**
