### PR TITLE
Adding Portugues from Portugal translation

### PR DESCRIPTION
**Pull request by joaopmatos**
Add the pt-rPT resource folder with its own strings.xml file.

### CODE REVIEW

**Comment by OmGodse** [comment]
Could you also translate the new resources I've added since you forked the repository? (You can look at the app for context)

```xml
<string name="date_format">Date format</string>
<string name="none">None</string>
<string name="relative">Relative</string>
<string name="absolute">Absolute</string>

<string name="export_backup">Export backup</string>
<string name="import_backup">Import backup</string>
```

**Comment by joaopmatos** [comment]
> Could you also translate the new resources I've added since you forked the repository? (You can look at the app for context)
> 
> ```
> <string name="open_link">Open link</string>
> <string name="more_options">More options</string>
> <string name="view_file">View file</string>
> 
> <string name="date_format">Date format</string>
> <string name="none">None</string>
> <string name="relative">Relative</string>
> <string name="absolute">Absolute</string>
> 
> <string name="export_backup">Export backup</string>
> <string name="import_backup">Import backup</string>
> ```

I've added them but I get a warning about _date_format, none, relative and absolute_ not being available in the default locale. Is that something for me to worry about?

**Comment by OmGodse** [comment]
No, nothing to worry about there

**Comment by joaopmatos** [comment]
I've updated the xml files with the strings you needed. Sorry for adding too many commits, I'm a beginner with version handling with Git, the last commit should do just what you needed.

**Comment by OmGodse** [comment]
I've released the version with the Portuguese translation and accredited you on [CONTRIBUTORS.md](https://github.com/OmGodse/Notally/blob/master/CONTRIBUTORS.md)

It'll take some time for it to appear on the Play Store and F Droid but you can get it now from the releases page.

**Pull request merged**
