### PR TITLE
Update Dutch translation

### PR DESCRIPTION
**Pull request by Jopie01**

### CODE REVIEW

**Comment by OmGodse** [comment]
Hi @Jopie01, you've also modified existing translations. Are they not accurate?

**Comment by Jopie01** [comment]
> you've also modified existing translations. Are they not accurate?

Correct, there are some spelling mistakes and some words needs their 'action' version. But it's a bit hard to tell where the translated string is used but we'll see when a new release comes out with this translation. I've looked where the string popped up and then tried to use the right word.

**Comment by OmGodse** [comment]
Alright, thanks.

Could you also add the translation for `send_feedback`?

**Comment by Jopie01** [comment]
@OmGodse, I added the the `send_feedback` translation. Hopefully it's okay now.

**Pull request merged**
