### PR TITLE
MakeList + general improvements

### PR DESCRIPTION
**Pull request by PhilKes**
I love your app, I just noticed some minor things that I know from Google Keep and would love to see in this app.
This PR contains many commits for different features/improvements, if you want I can separate them into multiple PRs.

**Improvements:**
* Replaced `ru.rambler.libs.swipe_layout.SwipeLayout` (not available anymore on jcenter by original maintainer) with `com.zerobranch.layout.SwipeLayout` since  it also offers programatic ways to open/close the swipe (see swipe feature below)
* When the add item button is clicked the keyboard is shown
* When you press the IME action key a new entry is inserted after the current one
* The `dateFormat` and `textSize` are used for the notes preview, edit activity and widget

**Features:**
* In the `MakeList` activity I moved the delete item to a button on the right (visible if `EditText`of that item is focused)
* The swipe right is now used to group/"indent" a note, I know and really like this feature from Google Keep. If an item is checked that has "children" below it, the children items are also checked
* A new preference for setting auto-sort for ListItems, again implemented based on Google Keep, where when I check an item it is moved to the end of the list (optional, is turned off by default)
* New Toolbar entries to un-/check all items and to remove all checked ListItems

Here's a video showcasing the new `MakeList` Activity layout, with the ability to group tasks, auto-sort and extended toolbar entries:

https://github.com/user-attachments/assets/2402e17b-2e50-4ec5-89e9-198e95f41c60

### CODE REVIEW

**Comment by CodeNomadHQ** [comment]
Great job on adding subtasks! I’ve already tested it and found it super useful for daily tasks. This was a feature I wanted to implement myself, so I’m really happy to see it done.

I also noticed that there haven’t been any updates to the app in the past few months. I was wondering if maybe we can use your repo to add some new features I’d like to improve as well.

**Comment by PhilKes** [comment]
> Great job on adding subtasks! I’ve already tested it and found it super useful for daily tasks. This was a feature I wanted to implement myself, so I’m really happy to see it done.
> 
> I also noticed that there haven’t been any updates to the app in the past few months. I was wondering if maybe we can use your repo to add some new features I’d like to improve as well.

Certainly! I am currently implementing an undo/redo feature, will probably push it in the next few days. We can definetely use my fork to further add features and fixes. I'm also thinking about adding encryption of some sort to the back ups and also saw a few other feature requests/bugs in the Google Play Store reviews.

**Comment by CodeNomadHQ** [comment]
Great to hear! I’ve already made some changes to the UI, including a full dark mode. Also, I encountered a crash when clicking on 'Add Task.' I’ve attached the logs and a short video to help troubleshoot. 

```
type: crash
osVersion: google/husky/husky:14/AP2A.240905.003/2024091900:user/release-keys
package: com.omgodse.notally.debug:54
process: com.omgodse.notally.debug
processUptime: 2323 + 97 ms
installer: com.android.packageinstaller
 
java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
at java.util.ArrayList.rangeCheckForAdd(ArrayList.java:845)
at java.util.ArrayList.add(ArrayList.java:517)
at com.omgodse.notally.recyclerview.ListManager.updateChildren(ListManager.kt:371)
at com.omgodse.notally.recyclerview.ListManager.add$app_debug(ListManager.kt:46)
at com.omgodse.notally.recyclerview.ListManager.add$app_debug$default(ListManager.kt:37)
at com.omgodse.notally.activities.MakeList.setupListeners$lambda$0(MakeList.kt:70)
at com.omgodse.notally.activities.MakeList.$r8$lambda$aVejR_ty9fwDeGmf0nZVuPIeVCI(Unknown Source:0)
at com.omgodse.notally.activities.MakeList$$ExternalSyntheticLambda0.onClick(D8$$SyntheticClass:0)
at android.view.View.performClick(View.java:7931)
at android.view.View.performClickInternal(View.java:7908)
at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
at android.view.View$PerformClick.run(View.java:30990)
at android.os.Handler.handleCallback(Handler.java:959)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loopOnce(Looper.java:232)
at android.os.Looper.loop(Looper.java:317)
at android.app.ActivityThread.main(ActivityThread.java:8623)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)

https://github.com/user-attachments/assets/757cad8a-1874-4769-b786-5b31cb2d7e5a


at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:894)
```

https://github.com/user-attachments/assets/10c838cb-94eb-4a96-af90-6ab8b3837db4

**Comment by PhilKes** [comment]
> Great to hear! I’ve already made some changes to the UI, including a full dark mode. Also, I encountered a crash when clicking on 'Add Task.' I’ve attached the logs and a short video to help troubleshoot.
> 
> ```
> type: crash
> osVersion: google/husky/husky:14/AP2A.240905.003/2024091900:user/release-keys
> package: com.omgodse.notally.debug:54
> process: com.omgodse.notally.debug
> processUptime: 2323 + 97 ms
> installer: com.android.packageinstaller
>  
> java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
> ...
> https://github.com/user-attachments/assets/757cad8a-1874-4769-b786-5b31cb2d7e5a
> 
> 
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:894)
> ```
> 
>  screen-20241001-002626.mp4

Thanks for testing it out and the video. I reworked the whole feature, refactored a lot and added extensive tests for the `ListManager`.
I opened a PR in my fork which I will merge into my master (see https://github.com/PhilKes/Notally/pull/1), I guess it will be an independent fork from their on.
You are welcome to open a PR for the dark mode and your translations.
I also enabled the Issues Tab in my fork, so we can tackle other issues/features there too.

**Comment by CodeNomadHQ** [comment]
I really appreciate all the time you put into reworking the feature and adding subtasks. It sounds like a solid plan to keep the project in your repo, especially since @OmGodse hasn't been active for a while. I already made some progress on the feature for linking a note in other notes, so when you click on a note, it opens that note. Do you still want to keep the same name, or are you considering a change? Also, what are your thoughts on the app package name, would you like to keep it the same?

**Comment by PhilKes** [comment]
> I really appreciate all the time you put into reworking the feature and adding subtasks. It sounds like a solid plan to keep the project in your repo, especially since @OmGodse hasn't been active for a while. I already made some progress on the feature for linking a note in other notes, so when you click on a note, it opens that note. Do you still want to keep the same name, or are you considering a change? Also, what are your thoughts on the app package name, would you like to keep it the same?

I think for now I will leave it as it is. Perhaps I will rename it to something like NotallyX somewhere down the line if the creator wont respond to this PR, similar to e.g. TelegramX being an alternative/advanced version to the "original" Telegram App.

**Comment by Semmelrocks** [comment]
Thanks for the improvements! One feature I really miss is the auto-sort of the note fields by last edit. So that my last edited notes are on top. I only can pin on my most used notes.

**Comment by PhilKes** [comment]
> Thanks for the improvements! One feature I really miss is the auto-sort of the note fields by last edit. So that my last edited notes are on top. I only can pin on my most used notes.

Thanks for the suggestion, I detached my fork, and I'm currently working on many new features/improvements, including more notes sorting options, see https://github.com/PhilKes/NotallyX/issues/29

Feel free to add any suggestions there 🙂

**Comment by OmGodse** [comment]
Hello @PhilKes, thank you for the improvements. Due to some personal reasons, I had not checked Notally for the past few months. I'm open to accepting most of them, but can you create individual pull requests for each feature? Please start with having `textSize` being used for the widget too

**Pull request closed without merging**
