### PR TITLE
added the arabic lang to nottly :)

### PR DESCRIPTION
**Pull request by aagradwan**
.

### CODE REVIEW

**Comment by afmbsr** [comment]
Very poor translation and full of misspellings

**Comment by OmGodse** [comment]
Really? Are you sure?

**Comment by afmbsr** [comment]
Yes, I'm sure, I just wanted to alert you on that.

**Comment by DaffyDiamond** [comment]
Unrelated, but is it possible to add a OLED black theme option? The current dark mode is pretty close to being black but not quite. Also another feature I'd like is to be able to have 0 lines of the notes showing (so basically zero preview for the note). Right now "1" is the minimum setting. (I hope I'm not bothering you too much with these requests)

**Comment by OmGodse** [comment]
> Yes, I'm sure, I just wanted to alert you on that.

I see, thanks for pointing it out :)

**Comment by OmGodse** [comment]
@DaffyDiamond I'll have to see about the 0 option but OLED is definitely off the table. Supporting OLED would require a lot of work as Notally relies heavily on elevation to distinguish elements, something which the Material Components library has first class support for through the use of elevation overlays.

**Pull request closed without merging**
