### PR TITLE
Czech translation

### PR DESCRIPTION
**Pull request by tomo90**

### CODE REVIEW

**Comment by OmGodse** [comment]
Could you please remove the first resource `app_name` and directly start with the `<!-- Fragment Titles -->`

**Comment by tomo90** [comment]
> Could you please remove the first resource `app_name` and directly start with the `<!-- Fragment Titles -->`

Done. Hope It's OK now.

**Comment by OmGodse** [comment]
Yes, it's great. Do you want me to accredit you by your Github username or something else?

**Comment by tomo90** [comment]
> Yes, it's great. Do you want me to accredit you by your Github username or something else?
Glad to hear that. Github username would be OK. :)

**Comment by OmGodse** [comment]
I've accredited you on [CONTRIBUTORS.md](https://github.com/OmGodse/Notally/blob/master/CONTRIBUTORS.md)

The translation will ship soon with the next update.

**Comment by tomo90** [comment]
Hi. I wanted to be sure before posting so I tested on multiple devices. The Czech translation does not apply when I run Notally. The app still uses English which is a default fallback I guess?

**Comment by OmGodse** [comment]
Are you talking about the version of the app available from the releases page and the Play Store or the one you've built yourself? Because I haven't yet released an update with the Czech translation.

**Comment by tomo90** [comment]
I'm using the F-Droid version. I was assuming that the v3.3 already includes the Czech translation. Everything is how It's supposed to be then. My bad,  appologies.

**Comment by OmGodse** [comment]
The version with the Czech translation is out on the Play Store now. It'll take a couple of days for it to come out on FDroid but you can get it from the releases page. (Both are the same files)

**Comment by tomo90** [comment]
> The version with the Czech translation is out on the Play Store now. It'll take a couple of days for it to come out on FDroid but you can get it from the releases page. (Both are the same files)

The translation works great. Now I get to enjoy Notally even more. :) Thank you.

**Comment by OmGodse** [comment]
You're welcome!

Could you please also translate the following phrases which'll be used in the upcoming update? (I'm attaching screenshots for context)

No need to make another pull request, you can just directly reply here.

Delete all
Delete all notes?

Delete all notes
Delete all

**Comment by tomo90** [comment]
Hi! Sure thing. Here goes the translation..

Delete all - Smazat vše
Delete all notes? - Smazat všechny poznámky?

**Pull request merged**
